//TYPES AUTH
export const SUCCESSFUL_REGISTRATION = "SUCCESSFUL_REGISTRATION";
export const ERROR_REGISTRATION = "ERROR_REGISTRATION";
export const GET_USER = "GET_USER";
export const SUCCESSFUL_LOGIN = "SUCCESSFUL_LOGIN";
export const ERROR_LOGIN = "ERROR_LOGIN";
export const LOGOUT = "LOGOUT";

//TYPES IMAGE
export const GET_IMAGES = "GET_IMAGES";
export const SUCCESS_GET_IMAGES = "SUCCESS_GET_IMAGES";
export const ERROR_GET_IMAGES = "ERROR_GET_IMAGES";
export const ADD_IMAGE = "ADD_IMAGE";
export const SUCCESS_ADD_IMAGE = "SUCCESS_ADD_IMAGE";
export const ERROR_ADD_IMAGE = "ERROR_ADD_IMAGE";
export const DELETE_IMAGE = "DELETE_IMAGE";
export const SUCCESS_DELETE_IMAGE = "SUCCESS_DELETE_IMAGE";
export const ERROR_DELETE_IMAGE = "ERROR_DELETE_IMAGE";
export const FILTER_IMAGE = "FILTER_IMAGE";
export const QUIT_FILTER_IMAGE = "QUIT_FILTER_IMAGE";
//TYPES MODAL
export const SHOW_MODAL = "SHOW_MODAL";
export const HIDE_MODAL = "HIDE_MODAL";
